name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

        # Unit + integration tests
      - name: Run unit and integration tests
        run: npm run test:run

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium firefox

      # E2E tests
      - name: Run E2E tests
        run: npm run test:e2e

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format

      - name: Build project
        run: npm run build
